import { Instagram, Facebook, MapPin, Phone, Mail, Clock } from "lucide-react";
import { Separator } from "@/components/ui/separator";

export default function Footer() {
  const iconLink = "flex h-10 w-10 items-center justify-center rounded-full bg-white/5 transition hover:bg-[#E5D3B3] hover:text-[#5D4037]";
  return <footer className="bg-[#5D4037] pb-7 pt-14 text-white md:pt-16">
    <div className="container mx-auto max-w-7xl px-5 sm:px-6">
      <div className="mb-12 grid gap-10 sm:grid-cols-2 lg:grid-cols-[1.1fr_0.9fr_0.9fr_1.25fr] lg:gap-8">
        <div><h3 className="mb-4 font-serif text-2xl font-bold tracking-tight text-[#E5D3B3]">MAROBEL</h3><p className="max-w-xs text-sm font-light leading-relaxed text-white/60">Tu santuario de belleza y bienestar en Guayaquil, diseñado para que cada visita se sienta especial.</p><div className="mt-5 flex gap-3"><a href="https://www.instagram.com/marobel.studio/" target="_blank" rel="noopener noreferrer" className={iconLink} aria-label="Instagram"><Instagram className="h-4 w-4" /></a><a href="#" className={iconLink} aria-label="Facebook"><Facebook className="h-4 w-4" /></a></div></div>
        <div><h4 className="mb-5 text-[10px] font-bold uppercase tracking-[0.3em] text-[#E5D3B3]">Contacto</h4><ul className="space-y-4 text-sm font-light text-white/60"><li className="flex items-start gap-3"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-[#E5D3B3]" /><a href="https://maps.app.goo.gl/7ciYuBG8zAVHtitv7?g_st=ac" target="_blank" rel="noopener noreferrer" className="hover:text-white">Marobel Beauty Studio, Guayaquil</a></li><li className="flex items-center gap-3"><Phone className="h-4 w-4 text-[#E5D3B3]" /><span>+593 96 927 2530</span></li><li className="flex items-center gap-3"><Mail className="h-4 w-4 text-[#E5D3B3]" /><span>hola@marobel.studio</span></li></ul></div>
        <div><h4 className="mb-5 text-[10px] font-bold uppercase tracking-[0.3em] text-[#E5D3B3]">Horarios</h4><ul className="space-y-4 text-sm font-light text-white/60"><li className="flex gap-3"><Clock className="mt-0.5 h-4 w-4 shrink-0 text-[#E5D3B3]" /><div><p className="font-semibold text-white">Lunes a Viernes</p><p>9:00 AM - 6:00 PM</p></div></li><li className="flex gap-3"><Clock className="mt-0.5 h-4 w-4 shrink-0 text-[#E5D3B3]" /><div><p className="font-semibold text-white">Sabados</p><p>10:00 AM - 6:00 PM</p></div></li><li className="text-xs italic text-[#E5D3B3]">Domingos: Cerrado</li></ul></div>
        <div><div className="mb-4 flex items-center justify-between"><h4 className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#E5D3B3]">Ubicacion</h4><a href="https://maps.app.goo.gl/7ciYuBG8zAVHtitv7?g_st=ac" target="_blank" rel="noopener noreferrer" className="text-[9px] font-bold uppercase tracking-widest text-[#E5D3B3] hover:text-white">Como llegar</a></div><div className="h-40 overflow-hidden rounded-2xl border border-white/10 shadow-lg"><iframe src="https://www.google.com/maps?q=V37W%2BWWW%20marobel.beautystudio%2C%20090507%20Guayaquil&output=embed" width="100%" height="100%" style={{ border: 0 }} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" title="Ubicacion de Marobel Beauty Studio"></iframe></div></div>
      </div>
      <Separator className="mb-6 bg-white/10" />
      <div className="flex flex-col items-center justify-between gap-4 text-center text-[9px] font-bold uppercase tracking-[0.25em] text-white/30 sm:flex-row"><p>© {new Date().getFullYear()} Marobel. Todos los derechos reservados.</p><div className="flex gap-6"><a href="#" className="hover:text-white">Privacidad</a><a href="#" className="hover:text-white">Terminos</a></div></div>
    </div>
  </footer>;
}
